-- ============================================================
--  The Gents Barber — setup de base de datos (Supabase / Postgres)
--  Ejecutar en: Supabase → SQL Editor → New query → Run
-- ============================================================

-- ---------- 1. TURNOS ----------
-- (probablemente ya existe; este bloque la crea si falta y asegura la
--  restricción única fecha+hora que usa el upsert de la app)
create table if not exists public.turnos (
  id        bigint generated by default as identity primary key,
  fecha     text not null,
  hora      text not null,
  estado    text not null default 'libre',   -- 'libre' | 'ocupado' | 'bloqueado'
  cliente   text default '',
  telefono  text default '',
  email     text default '',
  codigo    text default '',
  servicio  text default '',
  creado_en timestamptz default now()
);

-- Restricción única para el upsert onConflict('fecha,hora')
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'turnos_fecha_hora_key'
  ) then
    alter table public.turnos add constraint turnos_fecha_hora_key unique (fecha, hora);
  end if;
end $$;

-- ---------- 2. PRECIOS ----------
create table if not exists public.precios (
  servicio text primary key,
  precio   integer not null
);

insert into public.precios (servicio, precio) values
  ('Corte de pelo',       15000),
  ('Perfilado de barba',  20000),
  ('Barba completa',      22000),
  ('Tratamiento capilar', 30000),
  ('Corte + Barba',       36000)
on conflict (servicio) do nothing;

-- ---------- 3. CONFIG DE HORARIO DE TRABAJO ----------
create table if not exists public.config_horario (
  id     integer primary key default 1,
  inicio text not null default '09:00',
  fin    text not null default '20:00'
);

insert into public.config_horario (id, inicio, fin) values (1, '09:00', '20:00')
on conflict (id) do nothing;

-- ---------- 4. RLS / POLÍTICAS ----------
-- La app usa la anon key desde el navegador. Habilitamos lectura/escritura
-- pública en estas tablas (mismo modelo que ya usaba la app para turnos).
alter table public.turnos          enable row level security;
alter table public.precios         enable row level security;
alter table public.config_horario  enable row level security;

do $$
begin
  -- turnos
  if not exists (select 1 from pg_policies where tablename='turnos' and policyname='turnos_all') then
    create policy turnos_all on public.turnos for all using (true) with check (true);
  end if;
  -- precios
  if not exists (select 1 from pg_policies where tablename='precios' and policyname='precios_all') then
    create policy precios_all on public.precios for all using (true) with check (true);
  end if;
  -- config_horario
  if not exists (select 1 from pg_policies where tablename='config_horario' and policyname='config_all') then
    create policy config_all on public.config_horario for all using (true) with check (true);
  end if;
end $$;

-- ============================================================
--  Listo. La cuenta admin se crea en Authentication → Users
--  con el email: admin@thegentsbarber.com
-- ============================================================
